# Generated by Django 4.2.7 on 2023-11-25 18:28

from django.db import migrations, models
import shared.django.upload_images


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='https://telegra.ph/file/2e347ac7e04d279b5a019.png', upload_to=shared.django.upload_images.upload_image),
        ),
    ]
