# Generated by Django 4.2.7 on 2023-12-24 05:58

from django.db import migrations, models
import shared.django.upload_images


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, upload_to=shared.django.upload_images.upload_image),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
