name: Django CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  package-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x


  deploy-job:
    runs-on: ubuntu-latest
    needs: [ package-job ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy
        if: ${{ job.status != 'failure' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SECRET_KEY_GITHUB }}
          script: |
            cd /var/www/chat_app/backend
            git pull
            source venv/bin/activate
            pip install -r requirements.txt
            python3 manage.py migrate
            systemctl restart chat_app.gunicorn.service
            systemctl restart chat_app.daphne.service
            systemctl reload nginx.service
      - name: Stop Workflow on Error
        if: ${{ job.status == 'failure' }}
        run: exit 1